### ISSUE TITLE
Using the action with a commit hash causes build failure

### ISSUE THREAD

**Issue by msfjarvis** [burrunan/gradle-cache-action#26]
Going by the considerations noted [here](https://julienrenaux.fr/2019/12/20/github-actions-security-risk/), I attempted to migrate all the actions I was using to their latest commit hashes but `gradle-cache-action` did not like the change, resulting in [this](https://github.com/msfjarvis/compose-lobsters/runs/1271658255) failure. Is it possible to support using the action from a commit hash?

Here are the changes I was attempting to make when the failure occured: https://github.com/msfjarvis/compose-lobsters/pull/45

**Comment by vlsi** [comment]
Hi there 👋 

The release files are one a separate branch, so you need to use commit hashes from the tags (e.g. https://github.com/burrunan/gradle-cache-action/releases )

The latest tag is https://github.com/burrunan/gradle-cache-action/tree/v1.5 (which is 03c71a8ba93d670980695505f48f49daf43704a6)
