### ISSUE TITLE
Reporting build scan could be optional

### ISSUE THREAD

**Issue by pjakubczyk** [burrunan/gradle-cache-action#28]
I just started to use the plugin and found that the build scan link appears each time after a build. It's a warning message.

I think this could be optional. It will generate less buzz on the reports page especially that build scan are used mostly in situations when something is wrong with the build (code or configuration)

**Comment by vlsi** [comment]
Thank you. Fixed in https://github.com/burrunan/gradle-cache-action/pull/30

**Comment by pjakubczyk** [comment]
@vlsi when do you have plan to make a public release ?

**Comment by vlsi** [comment]
This has been included in `v1.6` or `feb985ecf49f57f54f31920821a50d0394faf122` (see https://github.com/burrunan/gradle-cache-action/pull/31#issuecomment-740635745 )

**Comment by pjakubczyk** [comment]
Works like a charm. Thanks for great work!
