### ISSUE TITLE
Reporting distributionSha256Sum should be optional

### ISSUE THREAD

**Issue by pjakubczyk** [burrunan/gradle-cache-action#29]
I fully understand the intension to be super secure however at the moment all my builds are spammed with the warning about the value is not set.

I would like to disable the warning because AndroidStudio doesn't support this feature yet
https://github.com/gradle/gradle/issues/9361

**Comment by vlsi** [comment]
Thanks, this is fixed in https://github.com/burrunan/gradle-cache-action/pull/31
