### ISSUE TITLE
Could not find method beforeSettings() for arguments [...] on build of type org.gradle.invocation.DefaultGradle.

### ISSUE THREAD

**Issue by BrainStone** [burrunan/gradle-cache-action#33]
Hi. I just tried adding this action to one of my action files to speed up the pipelines by caching all the downloaded dependencies.

Pretty unexpectedly I get the following error message when any gradle task is invoked.

```
FAILURE: Build failed with an exception.

* Where:
Initialization script '/home/runner/.gradle/init.gradle' line: 6

* What went wrong:
A problem occurred evaluating initialization script.
> Could not find method beforeSettings() for arguments [init_eiwz59vorj50r19wcr0ymhsxm$_run_closure1@415a204d] on build of type org.gradle.invocation.DefaultGradle.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Error: A problem occurred evaluating initialization script.
> Could not find method beforeSettings() for arguments [init_eiwz59vorj50r19wcr0ymhsxm$_run_closure1@415a204d] on build of type org.gradle.invocation.DefaultGradle.
```

Full log: https://github.com/AuraDevelopmentTeam/InvSync/runs/1623878392?check_suite_focus=true

**Comment by BrainStone** [comment]
This is due to this line: https://github.com/burrunan/gradle-cache-action/blob/61348edb3ed90fd775bd9738ac6535163f5b8c4b/cache-proxy/src/main/kotlin/com/github/burrunan/gradle/proxy/CacheProxy.kt#L122

`beforeSettings` was only added in Gradle 6. Compare [Javadoc 6.7.1](https://docs.gradle.org/6.7.1/javadoc/org/gradle/api/invocation/Gradle.html) with [Javadoc 5.6.4](https://docs.gradle.org/5.6.4/javadoc/org/gradle/api/invocation/Gradle.html)

``beforeProject​`` might be an appropriate alternative.

**Comment by Spongman** [comment]
just curious: does this mean that `gradle-cache-action` requires a minimum gradle version?

**Comment by BrainStone** [comment]
Appears like it.

**Comment by Spongman** [comment]
ok thank. unfortunately it looks like i'm stuck with an old version for now. this could be the straw that breaks my back to upgrade ;-)

**Comment by vlsi** [comment]
`v1.8` (`a61b505b54af16ffe2d1d1f2388b46516a8f0f32`) should work with Gradle 5
