### ISSUE TITLE
Read-only cache option

### ISSUE THREAD

**Issue by BrainStone** [burrunan/gradle-cache-action#34]
It would be fairly useful to have an option to only download the cache and not to upload any changes.

A use case would be PRs. So they can still get the cache so they don't need download all depencies but the cache won't be uploaded in case they added malicious code to the build script that stores itself in the cache so it persists into normal builds.

**Comment by vlsi** [comment]
Hi. Can you please clarify?

GitHub cache works in such a way that PR jobs have their own namespace.
PR jobs can read both "default breach cache" and "their own PR caches", however, whatever cache push stays confined to PR-related cache storage.

In other words, `master` branch can't accidentally pick up PR cache.

The action knows that, so initially `master` cache is received, however, the update of the cache would be PR-local, and the action should push only the set of added/changed files. The rest would be reused from the `master` cache.

Does that make sense?

Do you still think the issue is relevant?

**Comment by BrainStone** [comment]
I see.  
That makes sense.

Ok. I would still have a use case for that. Namely that if two gradle runs happen in parallel they could end up overriding eachother. So for one I would like to only have a read only cache, and the other gets to write. Unless I misunderstand that as well.

**Comment by pjakubczyk** [comment]
I have a use case. Bigger Android projects with lots of opened Pull Requests might produce lots of cache entries. 
Github Actions has limit of 5 GB for Cache.

In that case the cache can be populated from the main branch and feature branches will pick what's possible to get from it. 
Better option would be to have bigger cache but it's not in our powers ;)

**Comment by vlsi** [comment]
> In that case the cache can be populated from the main branch and feature branches will pick what's possible to get from it

I believe that is exactly the way it currently operates.

Implementing read-only option should not be a problem, I just want to understand if it solves a true issue.

---

However, there might be another idea: "limit the upload size". For instance, set a hard limit "e.g. 20MiB" for PR-based jobs, then the cache would discard more uploads.

`max_upload_size=0` would effectively emulate the read-only mode.

**Comment by pjakubczyk** [comment]
that'd be a nice improvement
I asked Github using enterprise account how the cache ages for the repository, still not answer.
Yet I still believe big project can easily fill the 5GB within a day or less.

You can ping me when the option is available so I'll test it on big android project.

**Comment by pjakubczyk** [comment]
to finish my thought,
in my opinion if cache is filled within less than 24 hours means that when I start my PR on Tuesday and have to leave it for a while then going back on Wednesday/Thursday loses all the magic we want to have.

**Comment by vlsi** [comment]
I've pushed `v1.7` (`ed5fd9a2c33249e80e4d5d6080f5b63d07210285`) with `read-only` option support (the fix is bd67dbd9581480ba520d3722a5e482c3326bfdef).
I guess `read-only: ${{ github.ref != 'refs/heads/main' }}` should work as well.

Please let me know if it works for you.

**Comment by pjakubczyk** [comment]
I was thinking rather to disable push in Gradle. 
The `init.gradle` generated in https://github.com/burrunan/gradle-cache-action/blob/bbff155167ab6680679a31546d2e5e841cc1bb1a/cache-proxy/src/main/kotlin/com/github/burrunan/gradle/proxy/CacheProxy.kt#L168
sets `push = true`. 
What do you think to have it configurable ?

**Comment by vlsi** [comment]
Ha, that indeed makes sense.
`push=false` is not enough though to suppress `dependencies` cache, so both approaches are required.

**Comment by vlsi** [comment]
I've added `push=false` in `v1.9` (`97d1da428b1d9b4f4a0de9aa268c72ce1fe9ca69`), see b2dbff67b30ad45ff44ce79d869f46ca043d9ee5

**Comment by pjakubczyk** [comment]
yep, much better
![Screenshot 2021-03-09 at 14 48 04](https://user-images.githubusercontent.com/1167297/110480141-76dd9a80-80e6-11eb-83a5-c5c8d04ec38e.png)
on Monday I set it up for all builds and start gathering data.
I'll let you know what's the performance difference.

Thanks !

**Comment by pjakubczyk** [comment]
ok there's another thing to consider : )
While the `read-only` flag is set should it also disabled pushing to local file cache?
I checked such configuration
```
buildCache {
    local {
        enabled = true
        push = false
    }
}
```
makes all "pack" disabled
<img width="720" alt="Screenshot 2021-03-10 at 10 25 31" src="https://user-images.githubusercontent.com/1167297/110606900-f329b980-818a-11eb-8947-3ac3f955d6a6.png">

**Comment by vlsi** [comment]
I thought local cache should be fast anyway. However, in CI builds local `UP-TO-DATE` might indeed be good enough, so  disabling local cache for `read-only` might make sense indeed.

By the way, I see you have `local build cache` hits. How is it possible for `local build cache with push=false`? Who populates it?

**Comment by pjakubczyk** [comment]
The screenshot is from my computer not CI.

Local cache is fast but requires packing the task outputs.

**Comment by vlsi** [comment]
Please check `v1.10` (`cbdf4342ff988d143aa7a5aeceedffafb8c74bcf`)
