### ISSUE TITLE
Running on Apple Sillicon warns about Node version

### ISSUE THREAD

**Issue by infomiho** [burrunan/gradle-cache-action#50]
Running this action on a Mac Mini M1 produces the following warning:
```
The node12 is not supported on macOS ARM64 platform. Use node16 instead.
```

I believe we should just bump the Node.js version to v16 and test it out. Here's a PR for that https://github.com/burrunan/gradle-cache-action/pull/49

**Comment by vlsi** [comment]
Fixed in https://github.com/burrunan/gradle-cache-action/pull/49
