### ISSUE TITLE
How to segregate cache by branch, commit or pipeline

### ISSUE THREAD

**Issue by flelli** [burrunan/gradle-cache-action#55]
I can't find a way to have a separate cache for each pipeline/commit or branch.
I'm running several jobs, each with one Gradle task and I need them to share the cache only within the same pipeline or commit. As far as I can see there is no way to start fresh at every pipeline and for some reason pretty much all of my jobs are not executed as they are shown as `FROM-CACHE`. This is weirt because it also happens when I commit changes to Java source code.

I tried using the `job-id` argument (using the same value `${{ github.run_id }}` for all jobs in the pipeline, but nothing changes.

What am I missing here? Is there a way to achieve that? In other words, is there a way I can set the cache id?

**Comment by vlsi** [comment]
> FROM-CACHE

`FROM-CACHE` message comes from Gradle, and it means Gradle was able to found the relevant entry in the build cache.
Note: if you are sure `FROM-CACHE` causes miscompilation, then it is a severe Gradle bug.

Could you provide the pointer to the CI log where you change sources, and `compileJava` still becomes `FROM-CACHE`?

**Comment by vlsi** [comment]
In case you wonder, the primary cache key is already segregated by PR number / branch name (see https://github.com/burrunan/gradle-cache-action/blob/9b6592b6ae7419babd09042fd26a9557a3297866/layered-cache/src/main/kotlin/com/github/burrunan/gradle/cache/ActionsTriggerExtensions.kt#L25-L30 ), however, it is done to prevent polluting the cache by different branches (e.g. when the set of dependencies significantly differs between branch-1.x and branch-2.x)

**Comment by flelli** [comment]
Thanks a lot Vladimir for your prompt response.

I created a [test branch](https://github.com/mooltiverse/nyx/tree/fix/force-java-rebuild) for you to help me out here.
It has 3 commits with their separate pipeline runs:

1. [here](https://github.com/mooltiverse/nyx/actions/runs/3279350546) is the first branch commit
2. [here](https://github.com/mooltiverse/nyx/actions/runs/3279449158) is the second commit, with a dummy change to a Java source file as you can see by the [changes](https://github.com/mooltiverse/nyx/commit/8f1cb164bfb1512ccf85815ad05595ef6d85331d)
3. [here](https://github.com/mooltiverse/nyx/actions/runs/3279615434) is the third commit, reverting the previous dummy change (see the [changes](https://github.com/mooltiverse/nyx/commit/dd830d0fd6c51e4a740b49248dcc7ca4ec03db0d))

For this test purposes let'c only focus on the `java-assemble` step (which builds the artifacts) and the `java-unit-test` step (that runs tests when artifacts are changed).

The first pipeline is OK, it compiles Java sources and runs tests. This means, as you said, that a new cache is started and, as expected, [there is no previous cache to restore](https://github.com/mooltiverse/nyx/actions/runs/3279350546/jobs/5398985957) (see the _Init with Gradle_ job).

The second pipeline is also OK. It finds the cache from the previous run but it [builds Java artifacts](https://github.com/mooltiverse/nyx/actions/runs/3279449158/jobs/5399294516) (see the `:modules:java:main:assemble` task in _Assemble with Gradle_) and [runs unit tests](https://github.com/mooltiverse/nyx/actions/runs/3279449158/jobs/5399312984) (see the `:modules:java:main:test` task in _Run Java Unit Tests with Gradle_). 

The third pipeline doesn't work as I expect. Artifacts are [rebuilt](https://github.com/mooltiverse/nyx/actions/runs/3279615434/jobs/5399708780) correctly, but [tests are not executed](https://github.com/mooltiverse/nyx/actions/runs/3279615434/jobs/5399731553) as the `:modules:java:main:test` turns out to be restored `FROM-CACHE`.

I wonder if I'm missing anything here because, as you can see, it's a quite articulated build script and I could really benefit from the remote cache.
For these reasons it would be enough for me to just share the cache within the pipeline.

Thanks

**Comment by vlsi** [comment]
>but [tests are not executed](https://github.com/mooltiverse/nyx/actions/runs/3279615434/jobs/5399731553)

By default, Gradle caches test tasks: https://docs.gradle.org/current/userguide/caching_java_projects.html#integration_test_execution

In your case, `test` tasks notices that its classpath is the same as the one with the first execution, so the test task assumed there's no need to execute it.

It is pretty much the same as repeated `./gradlew test --build-cache` execution. After the first execution, `test` would be `FROM-CACHE`.

If you really need to re-execute tests (why?) you should consider adding inputs to the task. If the test task is for "integration tests" (== it depends on a third-party system), then you might want adding something like `outputs.upToDateWhen { false }`

**Comment by vlsi** [comment]
>The third pipeline doesn't work as I expect. Artifacts are [rebuilt](https://github.com/mooltiverse/nyx/actions/runs/3279615434/jobs/5399708780) correctly, but [tests are not executed](https://github.com/mooltiverse/nyx/actions/runs/3279615434/jobs/5399731553)

In other words, if the only thing your tests do is to verify if "2+2" equals 4, then there's no need to execute it again and again. That is why Gradle caches test tasks by default.

**Comment by flelli** [comment]
Thanks Vladimir, the above makes sense when java source files (and so classes) don't change but if Java source files have change I also expect tests to run again. Doesn't this make sense?

**Comment by vlsi** [comment]
The test uses **compiled** java classes which just happen to be the same. The tests do not use "source files".
As you show, you change comments only, so it is expected that test are not re-executed, since the resulting bytecode becomes the same if you change the source file multiple times.
