### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nyxi** [burrunan/gradle-cache-action#56]
Thank you for a neat and helpful action :)  Any plans to release a new version with the commit updating @actions/core? The action is producing a lot of warnings atm.

**Comment by tino-fernandez** [comment]
Would be very nice to get a new version avoiding the github deprecated features.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

<img width="1101" alt="Screen Shot 2022-11-14 at 09 42 03" src="https://user-images.githubusercontent.com/101345155/201614505-2f6e9bf5-e3f7-459d-9647-0d1c4fd128e9.png">

**Comment by vlsi** [comment]
I'm working on that

**Comment by vlsi** [comment]
Fixed in 1.15
