### ISSUE TITLE
Node.js version is deprecated

### ISSUE THREAD

**Issue by Vampire** [burrunan/gradle-cache-action#95]
> The following actions use a deprecated Node.js version and will be forced to run on node20: burrunan/gradle-cache-action@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by Vampire** [comment]
Indeed, but seems v1 was still pointing to v1.21 according to GHA log, thanks

**Comment by Vampire** [comment]
Btw. actually that should have been a `v2` change.
Bumping Node.js version is a breaking change, as custom runners that only have the previous Node version available break with that change. ;-)
I also had to learn that from users of my action.

**Comment by vlsi** [comment]
That is an interesting finding.
Would you suggest rolling back v1 and pushing it as v2?

**Comment by Vampire** [comment]
That's what I did indeed:
![image](https://github.com/user-attachments/assets/0477a343-6736-4bce-9afe-c35c3fb1244f)
